# Generated by Django 4.2.1 on 2023-06-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_del_producto', models.CharField(max_length=50, null=True)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('precio', models.CharField(max_length=50, null=True)),
                ('modelo', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
