# Generated by Django 4.2.1 on 2023-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nuevo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(null=True),
        ),
    ]
