# Generated by Django 4.2.1 on 2023-07-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_producto_imagen_producto_nuevo_producto_oferta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
