# Generated by Django 4.2.1 on 2023-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Solido', 'Solido'), ('Acústica', 'Acústica'), ('Eléctrica', 'Acústica'), ('bajo_cuatro_cuerdas', 'bajo_cuatro_cuerdas'), ('bajo_cinco_cuerdas', 'bajo_cinco_cuerdas'), ('bajo_activo', 'bajo_activo'), ('bajo_pasivo', 'bajo_pasivo')], max_length=50, null=True),
        ),
    ]
