# Generated by Django 4.2.1 on 2023-07-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clase',
            field=models.CharField(choices=[('Guitarra', 'Guitarra'), ('Bajo', 'Bajo')], max_length=50, null=True),
        ),
    ]
