# Generated by Django 3.2.13 on 2023-07-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_producto_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('guitarra_cuerpo_solido', 'guitarra_cuerpo_solido'), ('guitarra_acústica', 'guitarra_acústica'), ('guitarra_eléctrica', 'guitarra_eléctrica'), ('bajo_cuatro_cuerdas', 'bajo_cuatro_cuerdas'), ('bajo_cinco_cuerdas', 'bajo_cinco_cuerdas'), ('bajo_activo', 'bajo_activo'), ('bajo_pasivo', 'bajo_pasivo'), ('piano_media_cola', 'piano_media_cola'), ('piano_cola_entera', 'piano_cola_entera'), ('pianolas', 'pianolas'), ('bateria_acustica_mapex', 'bateria_acustica_mapex'), ('bateria_acustica_pearl', 'bateria_acustica_pearl'), ('bateria_acustica_sonor', 'bateria_acustica_sonor'), ('bateria_acustica_tama', 'bateria_acustica_tama'), ('bateria_electrica_alesis', 'bateria_electrica_alesis'), ('bateria_electrica_roland', 'bateria_electrica_roland'), ('cabezales_engl', 'cabezales_engl'), ('cabezales_marshall', 'cabezales_marshall'), ('cabezales_pavey', 'cabezales_pavey'), ('cabezales_evh', 'cabezales_evh'), ('caja_evh', 'caja_evh'), ('caja_engl', 'caja_engl'), ('caja_marshall', 'caja_marshall'), ('caja_pavey', 'caja_pavey'), ('audifonos', 'audifonos'), ('monitores', 'monitores'), ('parlantes', 'parlantes'), ('cables', 'cables'), ('microfono', 'microfono'), ('interfaces', 'interfaces'), ('mixers', 'mixers')], max_length=50, null=True),
        ),
    ]
