# Generated by Django 4.2.1 on 2023-06-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicProWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente'), ('guest', 'Invitado'), ('bodeguero', 'Bodeguero')], max_length=20),
        ),
    ]
