# Generated by Django 4.2.1 on 2023-07-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicProWeb', '0003_venta_ventaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VentaProducto',
        ),
    ]
