# Generated by Django 4.2.1 on 2023-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicProWeb', '0004_venta_cantidad_delete_ventaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
