# Generated by Django 4.2.1 on 2023-07-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicProWeb', '0005_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tranferencia',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
