# Generated by Django 4.2.1 on 2023-07-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicProWeb', '0007_rename_tranferencia_venta_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoVendeor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_cliente', models.EmailField(max_length=254, null=True)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('comentario', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
