# Generated by Django 4.2.1 on 2023-07-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicProWeb', '0008_contactovendeor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactoVendeor',
            new_name='ContactoVendedor',
        ),
    ]
