# Generated by Django 4.2.1 on 2023-07-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicProWeb', '0009_rename_contactovendeor_contactovendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactovendedor',
            name='serie_del_producto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
